groups:
  - name: AppAlerts
    rules:
      - alert: WARNING-HighThroughput
        expr: rate(hello_info_count_total[1m]) > 10
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: Increased info retrieval rate {{ $labels.value}} {{ $value }}
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: CRITICAL-HighThroughput
        expr: rate(hello_info_count_total[1m]) > 50
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: Increased info retrieval rate {{ $labels.value}} {{ $value }}
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: WARNING-SlowAvailabiltyCheck
        expr: booking_availability_check_time_seconds_count > 0.001
        for: 5s
        labels:
          severity: warning
        annotations:
          summary: Increased response time {{ $labels.value}} {{ $value }}
          description: "Response time for availability checks \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: CRITICAL-SlowAvailabiltyCheck
        expr: booking_availability_check_time_seconds_count > 0.0015
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: Increased response time {{ $labels.value}} {{ $value }}
          description: "Response time for availability checks \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: CRITICAL-MemoryFailure
        expr: container_memory_failures_total > 600
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: Increased memory failure {{ $labels.value}} {{ $value }}
          description: "Memory failures \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        
      - alert: CRITICAL-ComponentDown
        expr: booking_availability_check_time_seconds_count > 20
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: Componenet Down {{ $labels.value}} {{ $value }}
          description: "Component down \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"