{
 "title": "Booking Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Availability Check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Booking Availability Checks [5m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(booking_availability_checks_total[5m])"
    }
   ]
  },
  {
   "title": "Booking Availability Checks Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "booking_availability_checks_total"
    }
   ]
  },
  {
   "title": "Booking Creation TIme",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "booking_controller_check_availability_time_seconds_max"
    }
   ]
  },
  { "title": "Booking Creation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Booking Creation [5m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(booking_creation_attempts_total[5m])"
    }
   ]
  },
  {
   "title": "Booking Creation Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "booking_creation_attempts_total"
    }
   ]
  },
  {
   "title": "Booking Creation TIme",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "booking_controller_create_time_seconds_max"
    }
   ]
  },
  {
   "title": "App performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "spring_data_repository_invocations_seconds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "spring_data_repository_invocations_seconds_max"
      }
     ]
    },
    {
     "title": "spring_data_repository_invocations_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "targets": [
      {
       "expr": "spring_data_repository_invocations_seconds_count"
      }
     ]
    },
    {
     "title": "spring_data_repository_invocations_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "targets": [
      {
       "expr": "spring_data_repository_invocations_seconds_count"
      }
     ]
    }
   ]
  }
 ]
}