pipeline {
    agent any
    environment {
        DOCKER_PASSWORD = credentials("docker-password") // Folosește credentialul pentru autentificare Docker
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build' // Rulează comanda pentru a construi aplicația
            }
        }
    }

    tools {
        jdk 'jdk21' // Asigură-te că JDK-ul 21 este instalat în Jenkins și folosit în pipeline
    }
}
