global:
  resolve_timeout: 1m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_auth_username: 'ioan.anghel123@gmail.com'
  smtp_auth_password: ''
  smtp_require_tls: true
  smtp_hello: 'localhost'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'
  
receivers:
- name: 'email'
  email_configs:
  - to: 'ioan.anghel123@gmail.com'
    from: 'ioan.anghel123@gmail.com'
    send_resolved: true